### ISSUE TITLE
ANDI seems to take only 8 bits

### ISSUE THREAD

**Issue by rishikhan** [riscv/riscv-gcc#125]
The RISCV spec 2.2. says:

> ANDI, ORI, XORI are logical operations that perform bitwise AND, OR, and XOR on register rs1 and the sign-extended 12-bit immediate and place the result in rd.

This code fails
```
int main(int argc, char** argv)
{
  __asm__ volatile (
     "andi %0, %0, 0xfff"
    : "=r" (argc)
  );

  return (int ) argc;
}
```
If you replace 0xfff with 0xff or any 8 bit number, it succeeds.

How do we get 12 bits? 
NOTE: I understand the code will truncate the result in the return, but I'm just trying to make a simple example to show the problem.

If we look at the generated opcode for 0xff we get:
>   0:	0ff57513          	andi	a0,a0,255

 Note the top 4 bits don't seem to be settable.

**Comment by jim-wilson** [comment]
__asm__ volatile (
     "andi %0, %0, -1"
    : "=r" (argc)
   );
It is a sign extended value so the range is from -2048 to 2047.  0xffffffff will also work for a rv32 compiler, but not a rv64 compiler, but that isn't a 64-bit -1.

**Comment by rishikhan** [comment]
Thank you! That was the issue. I guess negative numbers don't make much sense in hexadecimal. I was trying to find a way to set bits and didn't realize it had to be converted into small integer to work.
