### ISSUE TITLE
[Question] about relocation types for riscv64

### ISSUE THREAD

**Issue by unicornx** [riscv/riscv-gcc#225]
Hello,
I am comparing relocation types between x86_64 and riscv64. Regarding  `R_X86_64_GLOB_DAT` and `R_X86_64_TLSDESC`, what's the corresponding items in riscv64?
Thanks in adv.

**Comment by jim-wilson** [comment]
Shrug.  I don't know x86_64 relocs very well.  But our psabi document is here
    https://github.com/riscv/riscv-elf-psabi-doc
There is probably not a one to one matching of relocs as the architecture and ABI are different.

**Comment by kuanlinchentw** [comment]
Hi,
As far as I know, R_X86_64_GLOB_DAT is used to create a GOT entry to save a global address.
The familiar items in riscv64 is R_RISCV_64.

R_X86_64_TLSDESC is used to save TLS symbol descriptor in x86 -mtls-dialect=gnu2.
RISCV has not support gnu2 dialect yet. Right?

**Comment by jim-wilson** [comment]
I don't know anything about tls dialiects.  But I see only aarch64 and x86 support the -mtls-dialect= option.

**Comment by unicornx** [comment]
@jim-wilson @kuanlinchentw Thank you all, I will close this issue.
