### ISSUE TITLE
vector intrinsics: state of explicit vector length

### ISSUE THREAD

**Issue by Syndace** [riscv/riscv-gcc#243]
Is my observation correct that the intrinsics currently only support implicit vl (through vsetvl and friends) and neither of the explicit variants (with or without the `_vl` suffix)?

**Comment by kito-cheng** [comment]
I guess I can update that in next week, I will reply this issue and made a simple announcement on riscv-sw mailing list.

**Comment by kito-cheng** [comment]
gcc has implemented explicit vector intrinsic API now and also bumped to https://github.com/riscv/riscv-gnu-toolchain,
welcome to test and report bug :)
