### ISSUE TITLE
The intrinsic API of vector extension of branch 'riscv-gcc-10.1-rvv-dev' is not identical with spec

### ISSUE THREAD

**Issue by rjiejie** [riscv/riscv-gcc#255]
e.g. 

The prototype of 'vle32_v_i32m1' is :

vle##SEW##ff_v_i##SEW##m##LMUL (const int##SEW##_t *a, word_type *new_vl, word_type vl)

but the spec https://github.com/riscv/rvv-intrinsic-doc describe it as:

vint32m1_t vle32_v_i32m1 (const int32_t *base, size_t vl);

**Comment by kito-cheng** [comment]
> vle##SEW##ff_v_i##SEW##m##LMUL (const int##SEW##_t *a, word_type *new_vl, word_type vl)

This declaration is used for `vle*ff_v_*` functions.
