### ISSUE TITLE
Lack vector intrinsic for fractional LMUL

### ISSUE THREAD

**Issue by rjiejie** [riscv/riscv-gcc#279]

**Comment by rjiejie** [comment]
@kito-cheng Is it reasonable?

**Comment by kito-cheng** [comment]
Ideally it should implement on GCC, but...we(SiFive) are not focus on implement that on GCC, so..feel free to contribute :p

**Comment by rjiejie** [comment]
looks gcc has been abandoned ？
we Alibaba would help this :)

BTW, please review another commit, it's the missing intrinsic for vector spec:
https://github.com/riscv/riscv-gcc/pull/277

**Comment by damonyu1989** [comment]
@kito-cheng 
I think the feature of LMUL < 1 is important for performance.

**Comment by rjiejie** [comment]
@kito-cheng 
please review the fractional LMUL intrinsics PR:
https://github.com/riscv/riscv-gcc/pull/284
