### ISSUE TITLE
Add option to disable divide but keep multiply

### ISSUE THREAD

**Issue by vanjoe** [riscv/riscv-gcc#5]
I'd like to add a command line option to disable divide, but enable divide, along the lines of -mmuldiv.

Could someone point me in the right direction to go about doing this?

**Comment by aswaterman** [comment]
You could look at -m[no-]fdiv and TARGET_FDIV, which is analogous (it suppresses fdiv/fsqrt on systems that otherwise have floating point).

**Comment by palmer-dabbelt** [comment]
This commit https://github.com/riscv/riscv-gnu-toolchain/commit/f7a71cd82aced98c12ae4badf2e318e8d4387fef turned on fdiv by default.  It's in the old repo, so the paths will be a bit off, but that's the file that specifies -m arguments.

**Comment by vanjoe** [comment]
Would splitting TARGET_MULDIV into TARGET_MUL and TARGET_DIV be a good thing from your perspective? I'm thinking if I end up merging changes back.

**Comment by aswaterman** [comment]
That sounds good for the internals, but we shouldn't abandon the old command-line option.

**Comment by vanjoe** [comment]
Yeah I understand that concern. but having -mmuldiv and -mno-idiv and perhaps -mno-imul looks redundant and or confusing
