### ISSUE TITLE
Fence should maybe use IO?

### ISSUE THREAD

**Issue by terpstra** [riscv/riscv-gcc#54]
When barriers get dropped by atomics and other C primitive, they only ever fence between memory. However, in userspace the compiler does not know you were operating on actually memory or a memory-mapped device paged in for you by some kernel driver. Therefore maybe a fence rw,rw should be fence rwio, rwio?

**Comment by aswaterman** [comment]
I'm OK with changing all the gcc fences to be conservative FENCE for now, until this is sorted out.
