### ISSUE TITLE
unrecognized command line option '-mmemcpy'

### ISSUE THREAD

**Issue by ilg-ul** [riscv/riscv-gcc#68]
The error messages are:

```
riscv64-unknown-elf-g++: error: unrecognized command line option '-mmemcpy'
riscv64-unknown-elf-g++: error: unrecognized command line option '-mno-memcpy'; did you mean '-Wno-cpp'?
```

This happens with:

```
$ opt/riscv64-unknown-elf-gcc-20170503-x86_64-apple-darwin/bin/riscv64-unknown-elf-gcc --version
riscv64-unknown-elf-gcc (GCC) 7.1.0
```

**Comment by palmer-dabbelt** [comment]
Sorry, it looks like this is a documentation bug.  I think when we removed the movmem patterns we removed the memcpy option as well.  We're ading the movmem patterns back in, see https://github.com/riscv/riscv-gcc/pull/67 .  That doesn't pass the test suite yet, but when it does I'll add the option back in.

**Comment by ilg-ul** [comment]
should I temporarily disable it in the plug-in? or a new version of the compiler will be released shortly?

**Comment by palmer-dabbelt** [comment]
I think it's best to disable it for now, the test failures might take a while to track down.

**Comment by ilg-ul** [comment]
> disable it for now

ok, disabled.

**Comment by jim-wilson** [comment]
This was fixed upstream.  The -mmemcpy option was removed from the RISC-V docs.
