### ISSUE TITLE
Redundant loads for bitfield accesses

### ISSUE THREAD

**Issue by michaeljclark** [riscv/riscv-gcc#87]
GCC is generating redundant loads for accesses to bitfields. Andrew Pinski mentioned that it would likely be due to SLOW_BYTE_ACCESS being set to 0. I've tested a patch and that seems to be true. Here is example codegen with gcc 7.2 patched to set SLOW_BYTE_ACCESS to 1 vs unpatched gcc 7.1

- https://cx.rv8.io/g/yuV7eq

Here is the comment from SPARC:

```
/* Nonzero if access to memory by bytes is slow and undesirable.
   For RISC chips, it means that access to memory by bytes is no
   better than access by words when possible, so grab a whole word
   and maybe make use of that.  */
#define SLOW_BYTE_ACCESS 1
```

Here is the patch to fix it:

- https://github.com/rv8-io/musl-riscv-toolchain/blob/master/patches/gcc-7.2-slow-byte-access.patch

The current code-gen seems non-optimal assuming most architectures would have cache lines were one word access is going to be faster than several byte and half accesses (including a word access in the pathological case).

This is the pathological test case:

```
struct foo {
 unsigned int a : 3;
 unsigned int b : 3;
 unsigned int c : 3;
 unsigned int d : 3;
 unsigned int e : 3;
 unsigned int f : 3;
 unsigned int g : 3;
 unsigned int h : 3;
 unsigned int i : 3;
 unsigned int j : 3;
};

unsigned int proc_foo(struct foo *p)
{
   return p->a + p->b + p->c + p->d + p->d + p->e + p->f + p->g + p->h + p->i + p->j;
}
```

**Comment by aswaterman** [comment]
https://github.com/riscv/riscv-gcc/pull/88

**Comment by michaeljclark** [comment]
Thx!
